name: BoosterPerks
version: '1.0.0'
description: 'Advanced perk system with GUI, database support, and admin tools'
author: 'YourName'
website: 'https://github.com/YourUsername/BoosterPerks'
main: com.example.perks.PerksPlugin
api-version: '1.20'
folia-supported: true

# Supported Minecraft versions: 1.20 - 1.21.8
depend: [Vault]
softdepend: []

commands:
  boosterperks:
    description: 'Open the perks menu or execute admin commands'
    usage: '/boosterperks [admin|add|remove|setprice|reload] [args...]'
    aliases: [bperks, bp, perks, perk]
    permission: boosterperks.use
  boostershop:
    description: 'Open the perk shop (redirects to main menu)'
    usage: '/boostershop'
    aliases: [bshop, perkshop, shop]
    permission: boosterperks.use

permissions:
  boosterperks.*:
    description: 'Gives access to all BoosterPerks features'
    default: op
    children:
      boosterperks.use: true
      boosterperks.admin: true
      boosterperks.perks.*: true
  
  boosterperks.use:
    description: 'Allows basic perk usage and menu access'
    default: true
  
  boosterperks.admin:
    description: 'Allows administrative perk commands and GUI access'
    default: op
    children:
      boosterperks.use: true
      boosterperks.admin.gui: true
      boosterperks.admin.setprice: true
      boosterperks.admin.give: true
      boosterperks.admin.remove: true
      boosterperks.admin.reload: true
  
  boosterperks.admin.gui:
    description: 'Access to admin GUI panels'
    default: op
  
  boosterperks.admin.setprice:
    description: 'Allows setting perk prices'
    default: op
  
  boosterperks.admin.give:
    description: 'Allows giving perks to players'
    default: op
  
  boosterperks.admin.remove:
    description: 'Allows removing perks from players'
    default: op
  
  boosterperks.admin.reload:
    description: 'Allows reloading plugin configuration'
    default: op

  # Individual perk permissions
  boosterperks.perks.*:
    description: 'Gives access to all perks'
    default: false
    children:
      boosterperks.perks.telekinesis: true
      boosterperks.perks.glow: true
      boosterperks.perks.no-hunger: true
      boosterperks.perks.lavaresistance: true
      boosterperks.perks.no-fall: true
      boosterperks.perks.waterbreath: true
      boosterperks.perks.keepxp: true
      boosterperks.perks.keepinventory: true
      boosterperks.perks.speed: true
      boosterperks.perks.nightvision: true
      boosterperks.perks.jump: true
      boosterperks.perks.haste: true
      boosterperks.perks.fly: true
      boosterperks.perks.instantsmelt: true

  # Individual perk permissions
  boosterperks.perks.telekinesis:
    description: 'Allows using the Telekinesis perk'
    default: false
  boosterperks.perks.glow:
    description: 'Allows using the Glow perk'
    default: false
  boosterperks.perks.no-hunger:
    description: 'Allows using the No Hunger perk'
    default: false
  boosterperks.perks.lavaresistance:
    description: 'Allows using the Lava Resistance perk'
    default: false
  boosterperks.perks.no-fall:
    description: 'Allows using the No Fall perk'
    default: false
  boosterperks.perks.waterbreath:
    description: 'Allows using the Water Breath perk'
    default: false
  boosterperks.perks.keepxp:
    description: 'Allows using the Keep XP perk'
    default: false
  boosterperks.perks.keepinventory:
    description: 'Allows using the Keep Inventory perk'
    default: false
  boosterperks.perks.speed:
    description: 'Allows using the Speed perk'
    default: false
  boosterperks.perks.nightvision:
    description: 'Allows using the Night Vision perk'
    default: false
  boosterperks.perks.jump:
    description: 'Allows using the Jump perk'
    default: false
  boosterperks.perks.haste:
    description: 'Allows using the Haste perk'
    default: false
  boosterperks.perks.fly:
    description: 'Allows using the Fly perk'
    default: false
  boosterperks.perks.instantsmelt:
    description: 'Allows using the Instant Smelt perk'
    default: false
