name: Perks
version: 1.0
main: com.example.perks.PerksPlugin
api-version: '1.20'
commands:
  perks:
    description: Manage and toggle perks
    usage: /perks
    aliases: [perk]
  perkshop:
    description: Open the perk shop
    usage: /perkshop
permissions:
  nitroperks.admin:
    description: Allows administrative perk commands
    default: op
